import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import "/node_modules/primeflex/primeflex.css";
import { PrimeReactProvider } from "primereact/api";

import AuthenticatedGuard from "@/components/authguard/AuthenticatedGuard";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aide Budget",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
      {/* <AuthenticatedGuard> */}
          <PrimeReactProvider>
            {children}
            </PrimeReactProvider>
            {/* </AuthenticatedGuard> */}
      </body>
    </html>
  );
}
